"""initial_schema

Revision ID: 2d720024b4e4
Revises: 
Create Date: 2025-11-01 10:44:51.302773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from backend.models.utils import GUID

# revision identifiers, used by Alembic.
revision: str = '2d720024b4e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PRODUCT_MANAGER', 'CONTRIBUTOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('organization_id', GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_id', GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', GUID(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('organization_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_org_timestamp', 'audit_logs', ['organization_id', 'timestamp'], unique=False)
    op.create_table('contexts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('organization_id', GUID(), nullable=False),
    sa.Column('company_mission', sa.Text(), nullable=True),
    sa.Column('strategic_objectives', sa.Text(), nullable=True),
    sa.Column('target_markets', sa.Text(), nullable=True),
    sa.Column('competitive_landscape', sa.Text(), nullable=True),
    sa.Column('technical_constraints', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'version', name='uq_org_version')
    )
    op.create_index(op.f('ix_contexts_organization_id'), 'contexts', ['organization_id'], unique=False)
    op.create_index('ix_org_current', 'contexts', ['organization_id', 'is_current'], unique=False)
    op.create_table('initiatives',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_QA', 'READY', 'MRD_GENERATED', 'SCORED', 'ARCHIVED', name='initiativestatus'), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('organization_id', GUID(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('context_snapshot_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_snapshot_id'], ['contexts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_initiatives_created_by', 'initiatives', ['created_by'], unique=False)
    op.create_index('ix_initiatives_org_status', 'initiatives', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_initiatives_organization_id'), 'initiatives', ['organization_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', 'TIMEOUT', 'RATE_LIMITED', name='llmcallstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('organization_id', GUID(), nullable=False),
    sa.Column('initiative_id', GUID(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_initiative_id'), 'llm_calls', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_organization_id'), 'llm_calls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_user_id'), 'llm_calls', ['user_id'], unique=False)
    op.create_index('ix_llmcalls_agent', 'llm_calls', ['agent_name', 'created_at'], unique=False)
    op.create_index('ix_llmcalls_initiative', 'llm_calls', ['initiative_id', 'created_at'], unique=False)
    op.create_index('ix_llmcalls_org_created', 'llm_calls', ['organization_id', 'created_at'], unique=False)
    op.create_table('mrds',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('initiative_id', GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('quality_disclaimer', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('completeness_score', sa.Integer(), nullable=True),
    sa.Column('readiness_at_generation', sa.Integer(), nullable=True),
    sa.Column('assumptions_made', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mrds_generated_at', 'mrds', ['generated_at'], unique=False)
    op.create_index(op.f('ix_mrds_initiative_id'), 'mrds', ['initiative_id'], unique=True)
    op.create_table('questions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('initiative_id', GUID(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('BUSINESS_DEV', 'TECHNICAL', 'PRODUCT', 'OPERATIONS', 'FINANCIAL', name='questioncategory'), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', name='questionpriority'), nullable=False),
    sa.Column('blocks_mrd_generation', sa.Boolean(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_initiative_id'), 'questions', ['initiative_id'], unique=False)
    op.create_index('ix_questions_initiative_iteration', 'questions', ['initiative_id', 'iteration'], unique=False)
    op.create_index('ix_questions_initiative_priority', 'questions', ['initiative_id', 'priority'], unique=False)
    op.create_table('scores',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('initiative_id', GUID(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('effort', sa.Float(), nullable=True),
    sa.Column('rice_score', sa.Float(), nullable=True),
    sa.Column('feasibility', sa.Integer(), nullable=True),
    sa.Column('desirability', sa.Integer(), nullable=True),
    sa.Column('viability', sa.Integer(), nullable=True),
    sa.Column('fdv_score', sa.Float(), nullable=True),
    sa.Column('rice_reasoning', sa.JSON(), nullable=True),
    sa.Column('fdv_reasoning', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.Column('scored_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scored_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_initiative_id'), 'scores', ['initiative_id'], unique=True)
    op.create_table('answers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('question_id', GUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_status', sa.Enum('ANSWERED', 'UNKNOWN', 'SKIPPED', name='answerstatus'), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('answered_by', GUID(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_scores_initiative_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_questions_initiative_priority', table_name='questions')
    op.drop_index('ix_questions_initiative_iteration', table_name='questions')
    op.drop_index(op.f('ix_questions_initiative_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_mrds_initiative_id'), table_name='mrds')
    op.drop_index('ix_mrds_generated_at', table_name='mrds')
    op.drop_table('mrds')
    op.drop_index('ix_llmcalls_org_created', table_name='llm_calls')
    op.drop_index('ix_llmcalls_initiative', table_name='llm_calls')
    op.drop_index('ix_llmcalls_agent', table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_user_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_organization_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_initiative_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_initiatives_organization_id'), table_name='initiatives')
    op.drop_index('ix_initiatives_org_status', table_name='initiatives')
    op.drop_index('ix_initiatives_created_by', table_name='initiatives')
    op.drop_table('initiatives')
    op.drop_index('ix_org_current', table_name='contexts')
    op.drop_index(op.f('ix_contexts_organization_id'), table_name='contexts')
    op.drop_table('contexts')
    op.drop_index('ix_audit_org_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
