"""
MRD (Market Requirements Document) model.
"""

import enum
import uuid
from datetime import datetime
from sqlalchemy import Column, Text, Integer, Enum, ForeignKey, DateTime, Index, JSON
from sqlalchemy.orm import relationship
from backend.models.utils import GUID

from backend.database import Base


class ExportFormat(str, enum.Enum):
    """MRD export formats."""
    MARKDOWN = "Markdown"
    PDF = "PDF"
    DOCX = "DOCX"


class MRD(Base):
    """
    Market Requirements Document generated from initiative Q&A.
    Includes quality disclaimers based on readiness.
    """
    __tablename__ = "mrds"

    # Primary key
    id = Column(GUID, primary_key=True, default=uuid.uuid4)

    # Initiative (one-to-one)
    initiative_id = Column(
        GUID,
        ForeignKey("initiatives.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True
    )

    # Content
    content = Column(Text, nullable=False)  # Markdown format (full MRD assembled from sections)
    sections = Column(JSON, nullable=True)  # Structured sections for multi-section generation
    quality_disclaimer = Column(Text, nullable=True)  # Prepended disclaimer based on readiness

    # Metadata
    version = Column(Integer, default=1, nullable=False)  # Track regenerations
    word_count = Column(Integer, nullable=True)
    completeness_score = Column(Integer, nullable=True)  # 0-100
    readiness_at_generation = Column(Integer, nullable=True)  # Snapshot of readiness score
    assumptions_made = Column(JSON, nullable=True)  # List of assumptions from Unknown answers

    # Timestamps
    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Generated by
    generated_by = Column(
        GUID,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )

    # Relationships
    initiative = relationship("Initiative", back_populates="mrd")
    generated_by_user = relationship("User", foreign_keys=[generated_by])

    # Indexes
    __table_args__ = (
        Index('ix_mrds_generated_at', 'generated_at'),
    )

    def __repr__(self):
        return f"<MRD(id={self.id}, initiative_id={self.initiative_id}, version={self.version})>"
