"""
Question model with priority classification (P0/P1/P2).
"""

import enum
import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, Integer, Enum, Boolean, ForeignKey, DateTime, Index
from backend.models.utils import GUID
from sqlalchemy.orm import relationship

from backend.database import Base


class QuestionCategory(str, enum.Enum):
    """Question categories for readiness scoring."""
    BUSINESS_DEV = "Business_Dev"
    TECHNICAL = "Technical"
    PRODUCT = "Product"
    OPERATIONS = "Operations"
    FINANCIAL = "Financial"


class QuestionPriority(str, enum.Enum):
    """Question priority levels for UX optimization."""
    P0 = "P0"  # Critical - blocks MRD generation if unanswered
    P1 = "P1"  # Important - significantly improves MRD quality
    P2 = "P2"  # Optional - nice-to-have details


class Question(Base):
    """
    Question generated by Knowledge Gap Agent.
    Includes priority classification for fast-path UX.
    """
    __tablename__ = "questions"

    # Primary key
    id = Column(GUID, primary_key=True, default=uuid.uuid4)

    # Initiative
    initiative_id = Column(
        GUID,
        ForeignKey("initiatives.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Question metadata
    iteration = Column(Integer, nullable=False)  # 1, 2, or 3
    category = Column(Enum(QuestionCategory), nullable=False)
    priority = Column(Enum(QuestionPriority), nullable=False)  # NEW: P0/P1/P2
    blocks_mrd_generation = Column(Boolean, nullable=False, default=False)  # Derived from P0

    # Question content
    question_text = Column(Text, nullable=False)
    rationale = Column(Text, nullable=False)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    initiative = relationship("Initiative", back_populates="questions")
    answer = relationship("Answer", back_populates="question", uselist=False, cascade="all, delete-orphan")

    # Indexes
    __table_args__ = (
        Index('ix_questions_initiative_priority', 'initiative_id', 'priority'),
        Index('ix_questions_initiative_iteration', 'initiative_id', 'iteration'),
    )

    def __repr__(self):
        return f"<Question(id={self.id}, priority={self.priority.value}, category={self.category.value})>"
